services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
